$ANSIBLE_VAULT;1.1;AES256
36663636653039356164613936336231383461646239393131333966613764323639626532663638
6237396135663936623735373730356163616136613332340a623163393435343566393938393261
38343133613733613639363538613962323835653234656632633263333065616438373434376133
6666323465333865310a373565323163623434626665353735373961393530643037386537633032
66323037303235303863613035303065643363663931383831336437646330346231663432376662
65363132326665393630643032616138656362356361333737333837313361353936323264373562
38306336373930333238313961613131646237353738323961313737623035656264386434623565
37653966346264613361343763333531363639393061346339323135373635653630663238653066
35666165623437623130623533343739396236396330666338643638653862636531666338343064
33613734316261616330316666376164323164613737626362366337373138376430613465383236
39376461643030393236643230663638333536646538306430623661386438313463383537393436
62626333633338306666643630343062626534353631623062313364353265656435313862373266
37333065313737313664623135396161343734303833646135313730303231326264653738653539
30353663636539363634363066363662363738316134346563646333666236333765653065303437
34653534383735373133643363623034616565383466626430303134623661383435623261656362
30626335386164623266353134636339363337626361623539653834613232613361373733373934
37343531643763663834386330653233306234373438353464613436666462353961333931306263
30376461653931323334363735616132336161666664636437333139666364313965643632663431
34306333643337646364383631353265333864326333316230663764623635626433353539313131
30366165353839623961356137666161326333346265346639663035383338333935393137653161
35386264653139376339323134313131366430386231306239333033396466653739383631343331
34656636663362316561313035386161356231313166663462313661303161643464353863373833
62393631643632346366343638666230656138663737386539376534623837326232303632333864
61366538303434633833343830653462383239613837633139393766646561393033373232616438
32363265646165623130373839626363633266646535663862636536393831356364373263623165
6166626635666435626261353737653263386532666130643533
