$ANSIBLE_VAULT;1.1;AES256
66356431313239333239633233323639636135623164326636306564353365646133363330356538
6333303438363564373565356463303032326237333539310a386365646235316264336339333832
32363636316430613138366464333565316262656337643566303132396339386262373466393934
3965643863656534350a336232336435386136666666663132346635316330363835356530656239
33333138323865646239343536633330313335396635376338353962326266376638333734633435
37303534633164633165316537333133303762636562303639366365373237653535333839643565
38346633333365323336643032613864343639336663613138616461633635623562366139643665
33636439383062366437646665373461636363393831303034303365323033366432663065356234
61363063363465303836643761653165376165633230326663326461373230666435666535383831
63353665376131346636636166373539623838383035653930363736656462303162333336636661
32363132333564616633643932323937653136383966333864366132616436373438393065343633
65346464623362613164356664303365313930363761333331663032383931643334633935363836
34396635343136616664663132353436356533636134396462346161353939323135336366313430
36383430363937333563323161383065353463333335323239333534303936343331646464643834
37636365386536313061656336313566376339376166386337376538356265356237376234393535
37356532386663346431656431623865623933353133396331353937316337643338323238336339
61333837663065626537386363303131343632623630333132323131633366666161306437636137
3030386134623234313661393137323530353063316361646533
